package com.jp.epms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Booking implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String accessory;
	private java.lang.String accessoryOwner;
	private java.lang.String bookingType;
	private java.util.List<com.jp.epms.Equipment> availableEquipments;
	private java.util.Date endDate;
	private java.lang.String equipmentCategory;
	private java.lang.String equipmentType;
	private java.util.Date etbDttm;
	private java.util.Date etuDttm;
	private java.lang.String location;
	private java.util.List<com.jp.epms.Equipment> matchingEquipments;
	private java.lang.String onBoard;
	private java.lang.String ownedEquipment;
	private int quantity;
	private java.lang.String reqCoCd;
	private java.util.Date startDate;
	private java.lang.String vslCategory;
	private java.lang.String vslName;

	public Booking() {
	}

	public java.lang.String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(java.lang.String accessory) {
		this.accessory = accessory;
	}

	public java.lang.String getAccessoryOwner() {
		return this.accessoryOwner;
	}

	public void setAccessoryOwner(java.lang.String accessoryOwner) {
		this.accessoryOwner = accessoryOwner;
	}

	public java.lang.String getBookingType() {
		return this.bookingType;
	}

	public void setBookingType(java.lang.String bookingType) {
		this.bookingType = bookingType;
	}

	public java.util.List<com.jp.epms.Equipment> getAvailableEquipments() {
		return this.availableEquipments;
	}

	public void setAvailableEquipments(
			java.util.List<com.jp.epms.Equipment> availableEquipments) {
		this.availableEquipments = availableEquipments;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public java.lang.String getEquipmentCategory() {
		return this.equipmentCategory;
	}

	public void setEquipmentCategory(java.lang.String equipmentCategory) {
		this.equipmentCategory = equipmentCategory;
	}

	public java.lang.String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(java.lang.String equipmentType) {
		this.equipmentType = equipmentType;
	}

	public java.util.Date getEtbDttm() {
		return this.etbDttm;
	}

	public void setEtbDttm(java.util.Date etbDttm) {
		this.etbDttm = etbDttm;
	}

	public java.util.Date getEtuDttm() {
		return this.etuDttm;
	}

	public void setEtuDttm(java.util.Date etuDttm) {
		this.etuDttm = etuDttm;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.util.List<com.jp.epms.Equipment> getMatchingEquipments() {
		return this.matchingEquipments;
	}

	public void setMatchingEquipments(
			java.util.List<com.jp.epms.Equipment> matchingEquipments) {
		this.matchingEquipments = matchingEquipments;
	}

	public java.lang.String getOnBoard() {
		return this.onBoard;
	}

	public void setOnBoard(java.lang.String onBoard) {
		this.onBoard = onBoard;
	}

	public java.lang.String getOwnedEquipment() {
		return this.ownedEquipment;
	}

	public void setOwnedEquipment(java.lang.String ownedEquipment) {
		this.ownedEquipment = ownedEquipment;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public java.lang.String getReqCoCd() {
		return this.reqCoCd;
	}

	public void setReqCoCd(java.lang.String reqCoCd) {
		this.reqCoCd = reqCoCd;
	}

	public java.util.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.lang.String getVslCategory() {
		return this.vslCategory;
	}

	public void setVslCategory(java.lang.String vslCategory) {
		this.vslCategory = vslCategory;
	}

	public java.lang.String getVslName() {
		return this.vslName;
	}

	public void setVslName(java.lang.String vslName) {
		this.vslName = vslName;
	}

	public Booking(java.lang.String accessory, java.lang.String accessoryOwner,
			java.lang.String bookingType,
			java.util.List<com.jp.epms.Equipment> availableEquipments,
			java.util.Date endDate, java.lang.String equipmentCategory,
			java.lang.String equipmentType, java.util.Date etbDttm,
			java.util.Date etuDttm, java.lang.String location,
			java.util.List<com.jp.epms.Equipment> matchingEquipments,
			java.lang.String onBoard, java.lang.String ownedEquipment,
			int quantity, java.lang.String reqCoCd, java.util.Date startDate,
			java.lang.String vslCategory, java.lang.String vslName) {
		this.accessory = accessory;
		this.accessoryOwner = accessoryOwner;
		this.bookingType = bookingType;
		this.availableEquipments = availableEquipments;
		this.endDate = endDate;
		this.equipmentCategory = equipmentCategory;
		this.equipmentType = equipmentType;
		this.etbDttm = etbDttm;
		this.etuDttm = etuDttm;
		this.location = location;
		this.matchingEquipments = matchingEquipments;
		this.onBoard = onBoard;
		this.ownedEquipment = ownedEquipment;
		this.quantity = quantity;
		this.reqCoCd = reqCoCd;
		this.startDate = startDate;
		this.vslCategory = vslCategory;
		this.vslName = vslName;
	}

}