package com.jp.epms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Equipment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date yom;

	private java.lang.String accessory;

	private java.lang.String accessoryOwner;

	private java.lang.String bookingReqMatch;

	private java.lang.String equipId;

	private java.lang.String equipmentCategory;

	private java.lang.String equipmentType;

	private java.lang.Boolean exactMatch;

	private java.lang.String longTermEquip;

	private java.lang.String mastType;

	private java.lang.String onBoard;

	private java.lang.String owner;

	private java.util.Date permitExpiryDate;

	private java.lang.Integer priority;

	private java.lang.String regNbr;

	private java.lang.String reqMatch;

	private java.lang.Boolean usedRecentlly;

	private java.lang.String utilizationBand;

	private java.lang.Integer utilizationHours;

	public Equipment() {
	}

	public java.util.Date getYom() {
		return this.yom;
	}

	public void setYom(java.util.Date yom) {
		this.yom = yom;
	}

	public java.lang.String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(java.lang.String accessory) {
		this.accessory = accessory;
	}

	public java.lang.String getAccessoryOwner() {
		return this.accessoryOwner;
	}

	public void setAccessoryOwner(java.lang.String accessoryOwner) {
		this.accessoryOwner = accessoryOwner;
	}

	public java.lang.String getBookingReqMatch() {
		return this.bookingReqMatch;
	}

	public void setBookingReqMatch(java.lang.String bookingReqMatch) {
		this.bookingReqMatch = bookingReqMatch;
	}

	public java.lang.String getEquipId() {
		return this.equipId;
	}

	public void setEquipId(java.lang.String equipId) {
		this.equipId = equipId;
	}

	public java.lang.String getEquipmentCategory() {
		return this.equipmentCategory;
	}

	public void setEquipmentCategory(java.lang.String equipmentCategory) {
		this.equipmentCategory = equipmentCategory;
	}

	public java.lang.String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(java.lang.String equipmentType) {
		this.equipmentType = equipmentType;
	}

	public java.lang.Boolean getExactMatch() {
		return this.exactMatch;
	}

	public void setExactMatch(java.lang.Boolean exactMatch) {
		this.exactMatch = exactMatch;
	}

	public java.lang.String getLongTermEquip() {
		return this.longTermEquip;
	}

	public void setLongTermEquip(java.lang.String longTermEquip) {
		this.longTermEquip = longTermEquip;
	}

	public java.lang.String getMastType() {
		return this.mastType;
	}

	public void setMastType(java.lang.String mastType) {
		this.mastType = mastType;
	}

	public java.lang.String getOnBoard() {
		return this.onBoard;
	}

	public void setOnBoard(java.lang.String onBoard) {
		this.onBoard = onBoard;
	}

	public java.lang.String getOwner() {
		return this.owner;
	}

	public void setOwner(java.lang.String owner) {
		this.owner = owner;
	}

	public java.util.Date getPermitExpiryDate() {
		return this.permitExpiryDate;
	}

	public void setPermitExpiryDate(java.util.Date permitExpiryDate) {
		this.permitExpiryDate = permitExpiryDate;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public java.lang.String getRegNbr() {
		return this.regNbr;
	}

	public void setRegNbr(java.lang.String regNbr) {
		this.regNbr = regNbr;
	}

	public java.lang.String getReqMatch() {
		return this.reqMatch;
	}

	public void setReqMatch(java.lang.String reqMatch) {
		this.reqMatch = reqMatch;
	}

	public java.lang.Boolean getUsedRecentlly() {
		return this.usedRecentlly;
	}

	public void setUsedRecentlly(java.lang.Boolean usedRecentlly) {
		this.usedRecentlly = usedRecentlly;
	}

	public java.lang.String getUtilizationBand() {
		return this.utilizationBand;
	}

	public void setUtilizationBand(java.lang.String utilizationBand) {
		this.utilizationBand = utilizationBand;
	}

	public java.lang.Integer getUtilizationHours() {
		return this.utilizationHours;
	}

	public void setUtilizationHours(java.lang.Integer utilizationHours) {
		this.utilizationHours = utilizationHours;
	}

	public Equipment(java.util.Date yom, java.lang.String accessory,
			java.lang.String accessoryOwner, java.lang.String bookingReqMatch,
			java.lang.String equipId, java.lang.String equipmentCategory,
			java.lang.String equipmentType, java.lang.Boolean exactMatch,
			java.lang.String longTermEquip, java.lang.String mastType,
			java.lang.String onBoard, java.lang.String owner,
			java.util.Date permitExpiryDate, java.lang.Integer priority,
			java.lang.String regNbr, java.lang.String reqMatch,
			java.lang.Boolean usedRecentlly, java.lang.String utilizationBand,
			java.lang.Integer utilizationHours) {
		this.yom = yom;
		this.accessory = accessory;
		this.accessoryOwner = accessoryOwner;
		this.bookingReqMatch = bookingReqMatch;
		this.equipId = equipId;
		this.equipmentCategory = equipmentCategory;
		this.equipmentType = equipmentType;
		this.exactMatch = exactMatch;
		this.longTermEquip = longTermEquip;
		this.mastType = mastType;
		this.onBoard = onBoard;
		this.owner = owner;
		this.permitExpiryDate = permitExpiryDate;
		this.priority = priority;
		this.regNbr = regNbr;
		this.reqMatch = reqMatch;
		this.usedRecentlly = usedRecentlly;
		this.utilizationBand = utilizationBand;
		this.utilizationHours = utilizationHours;
	}

}